include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - conditional_uri_does_not_exist
    - directives_ordering
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - omit_local_variable_types
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_single_quotes
    - secure_pubspec_urls
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
